### PR TITLE
changed groupIds in AddOrUpdateSingleMember from string to int[]

### PR DESCRIPTION
**Pull request by MikeSmithDev**
AddOrUpdateSingleMember wasn't adding people to groups. Changed groupIds to int array. Successfully added to one/multiple groups following change.

### CODE REVIEW

**Comment by MikeSmithDev** [comment]
Note, this works when there are groupIds, but errors when there are none ("NoneType object is  not iterable.). Currently working on AddNewMembers function (as is it errors with "Unable to parse JSON request"). Can fix the groupIds issue as part of the AddNewMembers function updates.

**Comment by kylegregory** [comment]
Hey @MikeSmithDev,

Thanks for the PR! I had been talking in #1 about how I'd like to move all POST and PUT operations to a class, where we can better structure the fields needed for a response. Could you give that a go for this one? If not, I'll have an update to Members within a few days.

Also, I'm toying with whether or not to have the base type lists be Arrays or Array Lists, e.g. using your example int[] vs List<int>. I'm more inclined to do List<int> because of it's capabilities. If you have any thoughts on that, would be open to suggestions.

**Comment by MikeSmithDev** [comment]
I'll go a bit more thoroughly through #1 and see if I can come up with
something.

As for the 2nd issue, I agree with you and would be more inclined to go
with a List.

**Comment by kylegregory** [comment]
Hey @MikeSmithDev,

I had some time to start working on Members. Have a look at the most recent commit and see what you think. I've worked on [AddOrUpdateSingleMember](https://github.com/kylegregory/EmmaSharp/blob/master/EmmaSharp/Methods/Members.cs#L162). See how it works on your end. I'm open to suggestions.

**Pull request closed without merging**
