### PR TITLE
Added new field AutomateFieldChanged to AddMembers Model

### PR DESCRIPTION
**Pull request by ginowit**
Added the boolean field for "automate_field_changes" to the AddMembers Model. This permits bulk add/updates to members to trigger field change automation workflows.

### CODE REVIEW

**Comment by kylegregory** [comment]
@ginowit Thanks. This is approved and will be included in a future release.

**Comment by ginowit** [comment]
Cool, glad to hear it. Fyi, I find EmmaSharp to be working very well and
easy to work with. I appreciate the detailed comments in the code.

**Comment by SwolTron3000** [comment]
Is there a time frame of when this release will be available?

**Comment by kylegregory** [comment]
@SwolTron3000 I'll try to get a update to the NuGet package in the next day or so. There were some other changes I wanted to wrap up in this release pertaining to Triggers and some other project cleanup.

**Pull request merged**
